version: '3'
services:
  app:
    container_name: "flask-app"
    restart: always
    build:
      context: app
    ports:
      - "5000"
    depends_on:
      - db

  db: #added
    image: mongo #added
    container_name: "mongodb"
    restart: always
    ports: # added
      - "27017:27017" # added
    volumes:
      - /data/db:/data/db #added

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    ports:
      - "80:80"
