version: '3'
services:
  app:
    build:
      context: app
    ports:
      - "5000"
    depends_on: #added
      - db

  db: #added
    image: mongo #added
    ports: # added
      - "27017:27017" # added
    volumes: #added
      - /data/db:/data/db #added

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    ports:
      - "80:80"
